### ISSUE TITLE
Use GLUE2 for ARC CEs in AutoBDII2CS Agent

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#100]
Hi Alex,

We'd like to start collecting the ARC CE details from GLUE2 instead of GLUE1. This will allow per-queue VO access to be defined properly (rather than just applying the VO list to all queues as we do now).

Regards,
Simon

**Comment by sfayer** [comment]
Could you please make two quick fixes to this?
 * Architecture is truncated to one char (see other ticket), but please just hardcode this to "x86_64" anyway as most sites don't set it properly.
 * The error message if ARC CE code throws an exception says something like "Error in HTCondor" rather than ARC.

**Comment by alexanderrichards** [comment]
yup, on it

**Comment by alexanderrichards** [comment]
hopefully fixed now

**Comment by sfayer** [comment]
It's looking good... Can you please work out how to disable ARC CEs from being picked up with the GLUE1 code? Then we'll do some final tests and this should be complete.

Can you please also comment the ConfigurationSystem & cfgPath import lines in Glue2ARCAPI.py in?

**Comment by alexanderrichards** [comment]
> It's looking good... Can you please work out how to disable ARC CEs from being picked up with the GLUE1 code? Then we'll do some final tests and this should be complete.

I though you might ask that... This might not be so straightforward. I'll see if there is an easy way to do this

**Comment by alexanderrichards** [comment]
> Can you please also comment the ConfigurationSystem & cfgPath import lines in Glue2ARCAPI.py in?

oops yes thats my bad, needed to comment it out for debugging

**Comment by sfayer** [comment]
I think there are two ways to detect ARC-CEs and ignore them. We have a ce_type variable:
https://github.com/ic-hep/GridPPDIRAC/blob/0fe4aacdba586e239c8b09100c06f19e771dda67/ConfigurationSystem/private/AutoResourceTools/CETypes.py#L98

Failing that, the ARC CEs always have "nordugrid" in the queue names, so you could ignore them that way...

**Comment by alexanderrichards** [comment]
Yes I saw this already but wasn't sure the best way to intercept it given it's in the __new__. I have now caught is as an exception, not sure it's the best approach but it should work.

**Comment by sfayer** [comment]
Hi Alex,

We tested this out, it seems to be almost there, with just a few minor issues left. It looks like you spelt "Exception" wrong in the new exception class base. It also seems to have problem where a small number of the "CE" entries flip-flop, for example:
```
2020-05-01 11:31:23 UTC Configuration/AutoBdii2CSAgent NOTICE: Modifying /Resources/Sites/LCG/LCG.UKI-NORTHGRID-LIV-HEP.uk/CE:   hepgrid5.ph.liv.ac.uk, hepgrid6.ph.liv.ac.uk -> hepgrid5.ph.liv.ac.uk
...
2020-05-01 11:31:26 UTC Configuration/AutoBdii2CSAgent NOTICE: Modifying /Resources/Sites/LCG/LCG.UKI-NORTHGRID-LIV-HEP.uk/CE:   hepgrid5.ph.liv.ac.uk -> hepgrid5.ph.liv.ac.uk, hepgrid6.ph.liv.ac.uk
```
This may not have actually been added by these changes, I'm not sure, could you please have a look? You should stil have access to diractest.grid.hep.ph.ic.ac.uk to run some tests if you want (drop me an e-mail if you can't remember how to access this node).

In about 5 months we should be able to drop the Glue1 code completely as the CREAM-CEs should be obsolete and gone by then.

Regards,
Simon

**Comment by alexanderrichards** [comment]
> In about 5 months we should be able to drop the Glue1 code completely as the CREAM-CEs should be obsolete and gone by then.

🥳 🎉

**Comment by alexanderrichards** [comment]
> Exception" wrong

interesting my IDE didn't pick this up!

**Comment by alexanderrichards** [comment]
Whats more worrying about your flip-flop example is that it appears to be setting the ce to a tuple of two ces!

**Comment by sfayer** [comment]
Yes, it's the CE value at the site level which contains a list of all CEs at the site. (I don't know why DIRAC needs this, perhaps we can convince the developers to deprecate it in favour of just using the names of all of the CEs that are defined?).

**Comment by alexanderrichards** [comment]
> Yes, it's the CE value at the site level which contains a list of all CEs at the site

ok I'll take a look
