### ISSUE TITLE
Use MockLdap for AutoBDIISEs?

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#101]
Hi Alex,

Would it be possible to use the MockLdap object from Glue2HTCondorAPI.py in AutoBDIISEs.py as well? The AutoBDIISEs bit fails on the import ldap on the newest versions of DIRAC, but I'm not sure if the MockLdap module has all of the functions required for the SEs. Could you please look at whether it would be usable here and use it if the ldap module fails to import if it is?

Regards,
Simon

**Comment by alexanderrichards** [comment]
Yes, as you say it's just a case of checking MockLdap has all the functionality

**Comment by alexanderrichards** [comment]
I'll give it a check

**Comment by alexanderrichards** [comment]
I'll look into this after https://github.com/ic-hep/GridPPDIRAC/pull/67 is merged as I can then use it for the new Glue2ARCAPI as well

**Comment by sfayer** [comment]
Hi Alex,

Can you please do this on top of the other patch and we'll test them together? (Our test nodes have been upgraded to a version of DIRAC without the ldap module now, so we're going to struggle to test the Glue2ARC patch otherwise).

Regards,
Simon

**Comment by alexanderrichards** [comment]
ok sure

**Comment by alexanderrichards** [comment]
> I'm not sure if the MockLdap module has all of the functions required for the SEs

Looks like it should all be fine. The functionality used is the same functionality I mocked from the python ldap module

**Comment by sfayer** [comment]
Hi Alex,

We're seeing the case where the attributes returned end up truncated to just the first character of the string again. Could you please try to resolve that?

Regards,
Simon

**Comment by alexanderrichards** [comment]
I'll take a look.

**Comment by alexanderrichards** [comment]
is this just the architecture attribute as mentioned in #100 or are there others?

**Comment by sfayer** [comment]
At least the CE hostnames in the HTCondor module too...

**Comment by alexanderrichards** [comment]
Since I haven't changed the HTCondor module except to move the MockLdap more centrally, was this the case before or has this change done it?

**Comment by sfayer** [comment]
The HTCondor module is working correctly with the real ldap module on the production server, so I think this change is the one that broke it (although we didn't systematically test this change specifically).

**Comment by alexanderrichards** [comment]
makes sense since this change enforces the use of MockLdap as per the specification.

**Comment by alexanderrichards** [comment]
try now

**Comment by marianne013** [comment]
It looks like the SE updates are broken. The srm dict in ldapsearch_bdii_ses only contains one SE ('None'), that does not bode well and the SEs are not updated.

**Comment by alexanderrichards** [comment]
ok I'll take a look
