### ISSUE TITLE
BannedCEs for ARC & HTCondor

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#103]
Hi Alex,

It looks like the AutoBDII2CS agent ARC/HTCondor modules don't consider the BannedCEs list. Would you be able to add this feature?
(Bonus points if you also connect up the "FixedMaxProcessors" setting/feature too).

Regards,
Simon

**Comment by alexanderrichards** [comment]
Sure I’ll take a look. I’m doing the summer school until Friday but I’ll look then. How was the LZ UKDC meeting?

Cheers
Alex

From: sfayer
Sent: 22 June 2020 14:29
To: ic-hep/DIRAC
Cc: Richards, Alexander J; Assign
Subject: [ic-hep/DIRAC] BannedCEs for ARC & HTCondor (#103)

This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list to disable email stamping for this address. 
 
Hi Alex,
It looks like the AutoBDII2CS agent ARC/HTCondor modules don't consider the BannedCEs list. Would you be able to add this feature?
(Bonus points if you also connect up the "FixedMaxProcessors" setting/feature too).
Regards,
Simon
