### ISSUE TITLE
Missing LDAP helper functions in newer DIRAC releases

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#104]
Hi Alex,

In DIRAC v7r1p19, a number of the old LDAP helper functions/classes have been removed. Can you please modify the AutoBdii2CS agent to cope with this? At the very least, the following things are gone:
 - DIRAC.Core.Utilities.Grid.ldapSE (Not actually used, only imported => Easy!)
 - DIRAC.Core.Utilities.Grid.ldapSEAccessProtocol

There may be more once those are fixed.

Regards,
Simon

**Comment by alexanderrichards** [comment]
ok I'll take a look.

**Comment by sfayer** [comment]
Hi Alex,
Is there any update on this? This blocks all of our future upgrades so will probably suddenly become critical at some point.
Regards,
Simon

**Comment by alexanderrichards** [comment]
I haven't done anything about this yet but by virtue of you prodding me I'll bump it up the list ;) I'll try and take a look today
