### ISSUE TITLE
Support for SGE/OGE with ARC

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#11]
The current queue config can't cope with SGE/OGE queues on ARC because it contains an extra "/". 

This is currently open upstream: https://github.com/DIRACGrid/DIRAC/issues/2063

**Comment by alexanderrichards** [comment]
https://github.com/DIRACGrid/DIRAC/blame/integration/ConfigurationSystem/Client/Helpers/Resources.py#L212

**Comment by marianne013** [comment]
Imperial now runs a new version of SGE which does not automatically include the offending '/' character.
Also asked the ARC developers for a patch, not clear if this will happen:
https://ggus.eu/?mode=ticket_info&ticket_id=121732
