### ISSUE TITLE
Improved CE2CS Agent

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#3]
The CE2CS agent is fairly useless at the moment. It just e-mails the admin if the CS settings don't match the resources it finds in the BDII. Instead of e-mailing someone, it'd be better just to make the changes directly, saving on admin time. It may be better to create this as a new agent (SyncGridResources?).

**Comment by alexanderrichards** [comment]
@sfayer this has been merged into GridPPDIRAC repo, should we close this now or leave it open?
