### ISSUE TITLE
dirac-wms-job-submit should have an option to write job ids to a logfile on submission

### ISSUE THREAD

**Issue by marianne013** [ic-hep/DIRAC#31]
dirac-wms-job-status has an option to read in job ids from a file, so it would be nice to have a matching option for the submit command

**Comment by sfayer** [comment]
Hmm, didn't I see a working version of this somewhere? If so we should get it merged and close this ticket...

**Comment by marianne013** [comment]
I'm sure I did this - didn't you even check and whinge about it wrt job collections ?

**Comment by sfayer** [comment]
Yes, this was merged in e353588836043beea56ceb8d13e5ca5aceeb15de.
