### ISSUE TITLE
DIRAC storage file paths for multiple VOs

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#34]
Each storage element has a path specified:
/Resources/StorageElements/<name>/AccessProtocol.1/Path = /pnfs/hep.ph.ic.ac.uk/data

When a user uploads a file, the LFN is appended to this path:
/pnfs/hep.ph.ic.ac.uk/data/vo/some_file

The problem is that the VO name in the LFN should be fully qualified, however some storage elements (mainly dCache and CASTOR) use the short name (or possibly _anything_). All this information is in the BDII, but currently ignored by bdii2CS.

To fix this, I think we need to add a mapping section to each StorageElement block in the config:
Mappings
{
  dteam = /pnfs/hep.ph.ic.ac.uk/data/dteam
  comet.j-parc.jp = /pnfs/hep.ph.ic.ac.uk/data/comet
}
If the first path element of the LFN (the full VO name) is in mapping, then this should be substituted when creating the PFN from the SE path. I.e. If the VO is found in the mappings, this value is used instead of the Path field. The mappings field can be fully populated from the glue1 schema.

**Comment by alexanderrichards** [comment]
@sfayer I think that we did this already so this ticket can be closed right?

**Comment by sfayer** [comment]
Yes, I think you're right...
