### ISSUE TITLE
Relative file paths for dirac-dms- commands

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#35]
The LFNs used for the DIRAC data management commands currently seem to require an absolute path name, the start of which is just (normally) the fully qualified VO name:
/dteam/s.fayer/dirac1

If a relative path is given, the client knows the VO name, so could expand this for the user as a nice extra feature. I.e.:
s.fayer/dirac1 can be automatically expanded to /dteam/s.fayer/dirac1.

**Comment by marianne013** [comment]
No demand for it.
