### ISSUE TITLE
SiteDirector fails for CEs with SI00 = 0

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#38]
With the SI00 parameter set to "0" in the configuration service, the word "value" is seemingly returned instead. This causes a failure on this line in SiteDirector.py ~line 232:
si00 = float(...)

Either the AutoBdii2CSAgent should just ignore CEs with the SI00 to 0 or the source of the mysterious "value" string should be found and fixed...

**Comment by alexanderrichards** [comment]
Closing this bug as it is old and hasn't been seen again. I will also remove the branch with the commit.

@sfayer please reopen if it is still an issue later down the track
