### ISSUE TITLE
AutoBdii2CSAgent fails for some sites with bad names

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#39]
At least one site has a name with four sections in it: LCG.egee.irb.hr.hr

This causes a failure here:
EXCEPT: <type 'exceptions.ValueError'>:too many values to unpack
EXCEPT:   File "/opt/dirac/DIRAC/Core/Base/AgentModule.py", line 317, in am_secureCall
EXCEPT:     result = functor( *args )
EXCEPT:
EXCEPT:   File "/opt/dirac/GridPPDIRAC/ConfigurationSystem/Agent/AutoBdii2CSAgent.py", line 104, in execute
EXCEPT:     self.diracSENameTemplate)
 EXCEPT:
EXCEPT:   File "/opt/dirac/GridPPDIRAC/ConfigurationSystem/private/AddResourceAPI.py", line 311, in checkUnusedSEs
EXCEPT:     siteDomain, siteName, siteCountry = diracSite.split('.')

**Comment by alexanderrichards** [comment]
@sfayer this is also fixed in the GridPPDIRAC repo
