### ISSUE TITLE
OS Compatibility Mapping for AutoBdii2CS

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#41]
We could do with mapping each new Queues "OS" parameter via a function to simplify it. An example function for doing it is:

```python
VER_RE = re.compile("([0-9])\.[0-9]+")

def map_os_ver(ver_in):
  matches = VER_RE.search(ver_in)
  if not matches:
    return None
  return "EL%s" % matches.group(1)
```

If this returns a string, that should be used in place of the OS version... If it returns None, a warning should be logged and the original string should be used.

**Comment by alexanderrichards** [comment]
See commit 81d66f29ab96991fcf933f09bbb0201623a6e1f0

**Comment by alexanderrichards** [comment]
@sfayer this was merged into the GridPPDIRAC repo, shall we close this now or leave it open?

**Comment by sfayer** [comment]
I think this is complete...
