### ISSUE TITLE
SEs expiring

### ISSUE THREAD

**Issue by marianne013** [ic-hep/DIRAC#54]
Apparently people rename their SEs. While they should be punished, we need some kind of mechanism that removes an SE that most definitely doesn't exist any more.
As this should a be very infrequent occurrence, I'm almost tempted for a warning by email solution, rather than an auto delete, but we need to keep an automated eye on it.

**Comment by sfayer** [comment]
I copied the LastSeen logic from the CEs... Now it just needs a function to send an e-mail out for SEs not seen in "threshold" days.

**Comment by sfayer** [comment]
Merged and tested on test server.
