### ISSUE TITLE
handling of error reports and action after errors in dirac

### ISSUE THREAD

**Issue by marcus-ebert** [ic-hep/DIRAC#58]
Hi,

during "./dirac-install -r v6r14p5 -i 27 -g 2015-09-03 " on a local machine, the lcg bundle couldn't be downloaded. The reason for this was that the OS on that machine wasn't supported and no correct lcg-bundle could be found.
However, at the end of the installation there was still the output  "DIRAC properly installed". Could this please be changed to show an error at the end if something during the installation didn't worked, or already abort the installation if something can't be downloaded?

In addition, would it be possible to implement tests of the current OS to see if dirac can be used on it and if a not supported OS is detected then an error/warning message is shown?

Another error that was not really understandable is the following:
"Failed to get local copy from any replicas\nError getting file from storage:
FN does not follow the DIRAC naming convention"

This happened when dirac-dms-get-file was executed when the lcg-bundle was not installed, but this isn't clear from the error output. It would be very helpful if this could be changed to something that indicates the real reason for the failure.

**Comment by marianne013** [comment]
Hi Marcus,

I'll look into it, but basically you didn't follow the instructions and then expected it to work, which is clearly user error.
I agree with you that better error handling would help, but the dirac-install script is provided centrally by diracgrid.org and this is out of my hands. For this you need to complain here:
https://groups.google.com/forum/?hl=en-GB#!forum/diracgrid-forum
or if you are feeling argumentative file a bug with:
https://github.com/DIRACGrid/DIRAC
I'm going to put a check into the install script[*] that is linked of the gridpp wiki, but this is all I have control over. 
([*]https://raw.githubusercontent.com/ic-hep/DIRAC-tools/master/install_dirac_ui.py), but from my point of view this is all I can do.

Cheers,
Daniela

**Comment by marcus-ebert** [comment]
Hi Daniela,

Thanks for implementing a check in the script and pointing to the more general dirac development places! 
I think the point was not that I expected it to work when doing something not supported, but that one could expect it is installed correctly when it  says it is properly installed. With the check you mentioned, it should avoid such confusion in the future.

Thanks!
  Marcus

**Comment by marianne013** [comment]
Added a check to the (GridPP) install script.
