### ISSUE TITLE
Multi-core CE support in AutoBDII2CS

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#63]
Hi,

Would it be possible to pick out the GlueHostArchitectureSMPSize field from the BDII when processing a CE in AutoBDII2CS. If this field is present and >1, then create a MaxProcessors field under the CE in the CS (at the same level as the architecture/LastSeen/CEType fields)?

There is a lot of other stuff required to make multicore work, but this would be a good initial step.

Regards,
Simon

**Comment by alexanderrichards** [comment]
sure thing, not a problem.
