### ISSUE TITLE
Sites field in JDL accepts typos as valid sites

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#65]
This causes the jobs to queue for ever. If the site has been banned, a proper error ("Inactive site") is generated, it would be nice for that to apply to typos as well (or even a "No valid sites" error instead) so that users don't wait a long time for jobs that are never going to run.

**Comment by alexanderrichards** [comment]
@sfayer I believe that the above commit implements the logic that we discussed

**Comment by alexanderrichards** [comment]
ok I think we are good

**Comment by alexanderrichards** [comment]
ok I think we are good to go with the testing. Let me know if it works of not.

**Comment by sfayer** [comment]
This all works and has been merged upstream.
