### ISSUE TITLE
Xrootd protocol support for AutoBDII2CS Agent

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#71]
We would like to register xrootd endpoints as well as SRM ones in the StorageElements section of resources. The logic should be:
 - If an SE has SRM support, it should be AccessProtocol.1.
 - If an SE has XRootD support it should be AccessProtocol.2, unless SRM is not supported, then it should be AccessProtocol.1.

The fields for the Xrootd protocol should be set as:
 - Protocol = root
 - ProtocolName = XROOT
 - Port = \<Whatever is advertised in the BDII\> (probably 1094)
 - Access = remote
 - Path = \<Same logic as SRM\>
 - SpaceToken = \<Same logic as SRM\>
 - Host = \<Same logic as SRM\>
The section will also need a copy of the VOPath information, just like SRM too.

**Comment by alexanderrichards** [comment]
right o, I'll look into this sometime today.

**Comment by sfayer** [comment]
Hi Alex,

This doesn't quite work... The problem is that SRM is a "Service" (which has an associated SE & set of VOs in the BDII), whereas xrootd is an "AccessProtocol" (which only has an SE).

We think the logic is going to need changing quite significantly... Instead of searching for SRM services for a given VO, it'll need changing to find SEs that support the VO. Then for each VO it should search for whether they have SRM support, or xrootd support (this could be slightly modular as there are also other protocols that work like that). The GlueSEAccessProtocolType for xrootd can be "root" or "xroot" in the BDII.

If multiple SRM or xrootd entries are found for a given SE, then the one on the default port should be favoured (8443 for SRM, 1094 for xrootd), failing that, the lowest numbered on should be preferred.

Regards,
Simon

**Comment by alexanderrichards** [comment]
I have included a PR that fixes the XRootD support that this issue is about. Any further SRM related changes I shall defer to another issue, possibly #56
