### ISSUE TITLE
Queue merging for AutoBDII2CS agent

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#72]
Hi Alex,

Would it be possible to keep track of the GlueSubClusterLogicalCPUs for each queue and then use this to calculate the MaxWaitingJobs and MaxTotalJobs fields? This should stop us overloading sites which advertise the whole cluster behind multiple CEs (which is most sites, because it's the only way the accounting actually works properly).

The algorithm is: For all queues at a given site:
  - Group the queues by GlueSubClusterLogicalCPUs (so that queues where this is set identically are grouped together).
  - Count the number of queues in each group, call this N.
 - Set MaxWaitingJobs = 2 * GlueSubClusterLogicalCPUs / N
 - Set MaxTotalJobs = 4 * GlueSubClusterLogicalCPUs / N

Regards,
Simon

**Comment by alexanderrichards** [comment]
hi @sfayer when trying to run some testing for this on my old dirac box at CERN I get the traceback below. Whats the magic yum command to update this?

```python
Traceback (most recent call last):
  File "AddResourceAPI.py", line 11, in <module>
    from DIRAC import gLogger, gConfig, S_OK, S_ERROR
  File "/opt/dirac/DIRAC/__init__.py", line 129, in <module>
    from DIRAC.FrameworkSystem.Client.MonitoringClient import gMonitor
  File "/opt/dirac/DIRAC/FrameworkSystem/Client/MonitoringClient.py", line 12, in <module>
    from DIRAC.Core.DISET.RPCClient import RPCClient
  File "/opt/dirac/DIRAC/Core/DISET/RPCClient.py", line 6, in <module>
    from DIRAC.Core.DISET.private.InnerRPCClient import InnerRPCClient
  File "/opt/dirac/DIRAC/Core/DISET/private/InnerRPCClient.py", line 5, in <module>
    from DIRAC.Core.DISET.private.BaseClient import BaseClient
  File "/opt/dirac/DIRAC/Core/DISET/private/BaseClient.py", line 8, in <module>
    from DIRAC.Core.DISET.private.Protocols import gProtocolDict
  File "/opt/dirac/DIRAC/Core/DISET/private/Protocols.py", line 4, in <module>
    from DIRAC.Core.DISET.private.Transports import PlainTransport, SSLTransport
  File "/opt/dirac/DIRAC/Core/DISET/private/Transports/SSLTransport.py", line 12, in <module>
    from DIRAC.Core.DISET.private.Transports.SSL.SocketInfoFactory import gSocketInfoFactory
  File "/opt/dirac/DIRAC/Core/DISET/private/Transports/SSL/SocketInfoFactory.py", line 14, in <module>
    from DIRAC.Core.DISET.private.Transports.SSL.SocketInfo import SocketInfo
  File "/opt/dirac/DIRAC/Core/DISET/private/Transports/SSL/SocketInfo.py", line 11, in <module>
    from DIRAC.Core.Security import Locations
  File "/opt/dirac/DIRAC/Core/Security/__init__.py", line 8, in <module>
    raise Exception( "pyGSI is not the latest version (installed %s required %s)" % ( GSI.version.__version__, requiredGSIVersion ) )
Exception: pyGSI is not the latest version (installed 0.5.0 required 0.6.3)
```

**Comment by sfayer** [comment]
Hmm, you probably need to update the grid externals bundle that DIRAC is using... There isn't any direct command to do that, it's basically a case of removing the Linux_x86_64_glibc-2.12 directory and then unpacking some new bundles there:

http://lhcbproject.web.cern.ch/lhcbproject/dist/Dirac_project/installSource/Externals-server-v6r4p3-Linux_x86_64_glibc-2.12-python27.tar.gz
http://lhcbproject.web.cern.ch/lhcbproject/dist/Dirac_project/lcgBundles/DIRAC-lcg-2016-10-04-Linux_x86_64_glibc-2.12-python27.tar.gz

**Comment by alexanderrichards** [comment]
So `GlueSubClusterLogicalCPUs` is advertised per CE not per queue so does the following algorithm make sense:

* group all CEs advertising the same `GlueSubClusterLogicalCPUs`
* calculate the total number of queues in the group N
* Set MaxWaitingJobs = 2 * `GlueSubClusterLogicalCPUs` / N
* Set MaxTotalJobs = 4 * `GlueSubClusterLogicalCPUs` / N

@sfayer, @marianne013 does this make sense?

**Comment by alexanderrichards** [comment]
issue abandoned, see post from @marianne013 https://github.com/ic-hep/GridPPDIRAC/pull/35#issuecomment-270691410 (also quoted below)

>After extensive testing Simon and me have come to the sad conclusion that there are just too many cases to contend with and we will just drop the issue.
>Sorry.
