### ISSUE TITLE
Some sites don't fill GlueCEPolicyMaxCPUTime

### ISSUE THREAD

**Issue by marianne013** [ic-hep/DIRAC#73]
This shows up in the bdii as 

GlueCEPolicyMaxCPUTime: 2147483647 (2^31 -1)
GlueCEPolicyMaxObtainableCPUTime: 2147483647

This should be translated into two days worth of CPU (2880 minutes).

**Comment by sfayer** [comment]
Fixed in GridPPDIRAC.
