### ISSUE TITLE
UserAndGroupsAgent fails with latest version of DIRAC/python

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#74]
Hi Alex,

The GridPP DIRAC UserAndGroups agent is failing with the following message since a python upgrade:
```
RuntimeError: Couldn't setup ANY SOAP clients
```

I added some debugging to get  the inner-exception (perhaps you can do this permeantely as part of your fix) and I get:
```
ERROR: Failed to setup VOMS client: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

My guess would be the newer version of python is trying to check the cert against the CA, but it looks like we haven't set the capath anywhere, so it fails. Can you please add capath in the same way that we get the hostcert/hostkey?

Regards,
Simon

**Comment by alexanderrichards** [comment]
yup I'll have a go at this.
