### ISSUE TITLE
Container support for DIRAC

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#79]
This is a long ticket... We can split it into multiple ones if needed. I think the following changes are needed. This will probably be such a large change we should base it against the next major release branch, rel-v6r18.

### Configuration System

Each CE should have a boolean flag to indicate whether it is expected to support containers:
/Resources/Sites/LCG/\<SiteName\>/CEs/\<CEName\>/Containers = True/False
If a site doesn't have a Containers field, then it should be assumed to be False.

Each SiteDirector should also have a "Containers = \<boolean\>" flag to enable container support for a given VO. This should also default to False if not specified.

A list of supported container platforms should be added. In the configuration this will be a string: i.e.:
/Resources/ContainerPlatforms = Singularity, Docker

A new dictionary of mappings should be added, this maps platforms to container paths (this will be known as the container map): /Resources/Containers
\<Platform\> = \<Path\>
i.e.: EL6 = /cvmfs/cernvm-prod.cern.ch/cvm3

It may be worth adding some functions into the Resource helpers to access the above (for use in all of the following code).

### Site Director

If the SiteDirector's Containers config setting is True then the following should be done, otherwise there should be no change in behaviour.

When a site director receives a job/jobqueue it submits pilots jobs to a site. During the selection phase, it filters CEs that only support the job's required platform. This filter would need adjusting so that if "Containers = True", then all of platforms from the container map should be added to the platform supported by the CE. The raw platforms (i.e. all of the entries from ContainerPlatforms) should also be added.

### Job Submission API

The Job API should be modified so that if a user submits a JDL containing a "Container = \<path\>" and a "Platform" which matches a ContainerPlatform, then the job should be accepted. If Platform isn't a ContainerPlatform, then having a Container entry is an error. Setting Platform to a ContainerPlatform without including a Container = \<path\> entry is also an error.

### Pilot

On starting, the pilot should contain a module which searches for container support... Initially this is just a module for searching for "singularity" on the $PATH. This should be adaptable enough that other container frameworks (docker) can be added in the future. All of the container frameworks detected should be appended onto a new LocalConfiguration "ContainerSupport" variable as a list. This list should be included in the platform dictionary sent to the matcher.

### Matcher

The matcher receives the pilot information, including the new "ContainerSupport" variable. The ContainerSupport variable should be filtered against the ContainerPlatforms variable, resulting in a list of container frameworks which are both supported and enabled. When selecting a job, instead of just using the pilot platform, if there is one of more container frameworks on the list, then all of the container map platforms and supported ContainerPlatforms should also be considered. This will require modifying the matcher so that multiple platforms can be matched (at the moment a pilot is expected to only return a single platform).

### Pilot (again)

Once the matcher has selected a job, it is returned to the pilot. The pilot should then do the following things:

  - If the job platform requirements match the native platform (note that the job platform may be any), maintain the old behaviour and just start the job like always.
  - Otherwise a container will need to be started:
     - If the job platform is a ContainerPlatform, then start the job using the user supplied Container Path from the JDL.
     - Otherwise select the (a?) matching container path from the container map for the job platform.
     - The "inner-pilot" should be started within the container. This is similar to the SudoCE or GlexecCE, but may need some modifications to stage files in/out of the container.

### Documentation

The above should be documented as an extra page for the "Read the docs" documentation (along with updates for all of the Configuration reference pages). This should explain the overview of using containers for administrators.

### WebAppDIRAC (Bonus Item / Extra Credit)

Add support for the Container JDL parameter to the Job Launchpad. When this is selected, the Platform parameter should also be displayed and pre-populated with the first ContainerPlatform if possible.

**Comment by alexanderrichards** [comment]
> (Bonus Item / Extra Credit)

love it! :wink:

**Comment by sfayer** [comment]
Closing this ticket as it's being moved to the main DIRAC tracker.
