### ISSUE TITLE
Update pilotTools.py

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#81]
Hi Alex,

I think our local copy of pilotTools.py (WorkloadManagementSystem/PilotAgent/pilotTools.py) is now a bit out-of-date... Nothing is broken, but we should probably keep it roughly in-sync. I'm tempted to drop out git-install patch soon so that we don't have to keep doing this, but I need to have a chat with you about doing that in person I think.

For now could you please re-sync the pilotTools against the upstream integration branch? (But also please don't overwrite my future patch, which I've already back-ported: https://github.com/DIRACGrid/DIRAC/pull/3352)

Regards,
Simon

**Comment by alexanderrichards** [comment]
will do

**Comment by alexanderrichards** [comment]
right, I slipped and made a PR against upstream DIRAC again oops. Anyway this is now done. It updates rel-v6r15 branch with the changes that you made in your `pilot_pythonpath_fix` branch cherry-picked such that it should should not overwrite your changes in https://github.com/DIRACGrid/DIRAC/pull/3352
