### ISSUE TITLE
Extract VAC information from the GOCDB

### ISSUE THREAD

**Issue by marianne013** [ic-hep/DIRAC#86]
Once we get Manchester  to actually provide at least one proper entry for their VACs,

**Comment by sfayer** [comment]
Hi Alex,

Perhaps you could have a go at this? We basically want a new agent that does the following:
 - Read a config option for a list of "VOkeys" to search for (This can default to "GridPP").
 - Scan through the GOCDB looking for all services of type uk.ac.gridpp.vac or ...vcycle.
 - For each GOCDB service found, for each VOKey, see if it has an extension key "PILOT_DN_<vokey>", if it doesn't, ignore it.
 - If it does, add two entries, one for the site/service in Resources/Sites/VAC (or CLOUD), one in Registry/Hosts. (There are lots of examples of these manually defined in our production DIRAC config).
 - Do the LastSeen processing on all of these entries (just like CEs/SEs).
(Making sure no duplicates are added, etc... All of the usual stuff).

At the moment only our VCycle site has the special property for testing:
https://goc.egi.eu/portal/index.php?Page_Type=Service&id=9914

I guess the agent can be called AutoVac2CSAgent or something like that.

Regards,
Simon

**Comment by sfayer** [comment]
Hi Alex,

For the SE bit... I've added an extension to the site on gocdb in the form PILOT_SE_<votag> containing the SE string.

Regards,
Simon

**Comment by alexanderrichards** [comment]
Thanks Simon. For the GOCDBClient fix, please see the branch below:
https://github.com/ic-hep/DIRAC/tree/gocdbclient_extensions_fix
