### ISSUE TITLE
Need to change reliance on UsersAndGroups.py

### ISSUE THREAD

**Issue by alexanderrichards** [ic-hep/DIRAC#96]
Seems upstream have deprecated this module without warning, see:
https://github.com/DIRACGrid/DIRAC/commit/ac9a92c21ced2536e32ba06cbae35194d21de339#diff-e77bf7ace1d568fbc5bfa2470d6f8c18

**Comment by marianne013** [comment]
Here is the matching pull request.
https://github.com/DIRACGrid/DIRAC/pull/3640

**Comment by sfayer** [comment]
Full error message for this was simply the module being missing:
```
2020-05-05 11:28:03 UTC Framework/SystemAdministrator ERROR: Can't load UsersAndGroupsAgent
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/Base/private/ModuleLoader.py", line 214, in __recurseImport
    impModule = imp.load_module(modName[0], *impData)
  File "/opt/dirac/GridPPDIRAC/ConfigurationSystem/Agent/UsersAndGroupsAgent.py", line 8, in <module>
    from DIRAC.ConfigurationSystem.Agent.UsersAndGroups import UsersAndGroups
ImportError: No module named UsersAndGroups
```
Our module will either need a static copy of the old file that we then maintain, or updating to use functions that are available in the current version of DIRAC.

**Comment by sfayer** [comment]
Fixed:
https://github.com/ic-hep/GridPPDIRAC/commit/67d98481ab0baf7cd954a27a9fd8643db49e1e7a

The missing base module wasn't actually used, so I've just converted it to use the standard DIRAC Agent base instead.
